package string;

/**
 * Date 26.06.2020.
 *
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * https://leetcode.com/problems/find-the-difference/
 */

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] arr = new int[26];

        for (char c : s.toCharArray()) {
            arr[c-'a']++;
        }

        for (char c : t.toCharArray()) {
            arr[c-'a']--;

            if (arr[c-'a'] == -1)
                return c;
        }

        return 'a';
    }
}
